name: ena_mobile_front
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  xml: ^6.5.0
  shared_preferences: ^2.3.2
  youtube_player_iframe: ^5.2.1
  webview_flutter: ^4.9.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.1.1
  provider: ^6.1.2
  google_generative_ai: ^0.4.6
  intl: ^0.20.2
  permission_handler: ^11.3.1
  pdf: ^3.11.1
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.4

#carousel_slider:
#  git:
#    url: https://github.com/sergiandreplace/carousel_slider.git
#    ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icon/
      - .env

# Configuration de l'icône adaptative MyENA
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  
  # Icône adaptative pour Android (s'adapte aux couleurs système)
  adaptive_icon_background: "#3678FF"  # Bleu ENA qui s'adaptera aux palettes
  adaptive_icon_foreground: "assets/icon/MyENA.png"  # Votre logo
  
  # Icône standard pour iOS et fallback Android
  image_path: "assets/icon/MyENA.png"
  
  # Configuration avancée
  min_sdk_android: 21